---
title: "DSassignment_ggplot"
author: "Judy Ban"
date: "February 15, 2018"
output: html_document
---
Before attempting any exercise:  


metadata = read.table (file="Saanich.metadata.txt", header=TRUE, row.names=1, sep="\t", na.strings=c("NAN","NA","."))

#Exercise 1
- plot the points with NO2_uM values on the x-axis and Depth_m values on the y-axis  


ggplot(metadata, aes(x=NO2_uM, y=Depth_m)) +
  geom_point()

- Change points into purple and triangles  


ggplot(metadata, aes(x=NO2_uM, y=Depth_m)) +
  geom_point(color="purple", pch=17)

#Exercise 2  
- changing temperature from celsius to fehrenheit  


temperature=metadata %>% 
  mutate(Temperature_F = Temperature_C*1.8+32)  

- Plotting the temperature in F on the x axis and Depth_m on the Y axis  


ggplot(temperature, aes(x=Temperature_F, y=Depth_m)) +
  geom_point()
  
#Exercise 3  
- load physeq  


physeq  

- transform absolute abundance into percent abundance  


physeq_percent = transform_sample_counts(physeq, function(x) 100 * x/sum(x))  

- plotting the genus level communities by depth with respect to percent abundance  


plot_bar(physeq_percent, fill="Genus")  

- removing the black lines on the bars, and making the lables of the axis as well as the title more descriptive  


plot_bar(physeq_percent, fill="Genus") + 
  geom_bar(aes(fill=Genus), stat="identity") + labs( x = "Sample depth", y = "Percent relative abundance",
                                                       title ="Genus from 10 to 200 m in Saanich Inlet")  
                                                       
#Exercise 4  
- manipulating the metadata so that the nutrients of interest, H4_uM,NO2_uM,NO3_uM,O2_uM,PO4_uM,SiO2_uM, are all in one variable. Turn the table into an object called "gather".The column with the nutrient information is named "nutrients" and the column with values corresponding the the nutrients is called "uM".  


gather=gather(metadata, nutrients, uM, NH4_uM,NO2_uM,NO3_uM,O2_uM,PO4_uM,SiO2_uM)  



- plotting the graphs with lines and points  


ggplot(gather, fill="nutrients") +
  geom_line(aes(x=Depth_m, y=uM), stat="identity") + 
  geom_point(aes(x=Depth_m, y=uM), stat="identity") +
  facet_wrap(~nutrients, scales="free_y") +
  theme(legend.position="none")


